### PR TITLE
fix: added fix for dependency issue and some warnings

### PR DESCRIPTION
**Pull request by abhinav-from-contentstack**
- resolved dependency issues
- added `allowJs: true` to tsconfig.json for warnings generated while running unit tests
- changed `objectHashIgnoreUnknownHack` to false

### CODE REVIEW

**Comment by nadeem-cs** [comment]
Hey @abhinav-from-contentstack , the SRE restricts merging any feature branch to master branch directly. Please change this PR's base branch to [next](https://github.com/contentstack/contentstack-utils-javascript/tree/next)

**Comment by abhinav-from-contentstack** [comment]
the workflow is still reading the base branch as `master`

**Comment by nadeem-cs** [comment]
@abhinav-from-contentstack The action seems to be taking the original base branch. Let's close this and raise a fresh PR.

**Review by harshithad0703 — DISMISSED** [review]

**Comment by abhinav-from-contentstack** [comment]
Closing this PR as the `Check branch` github action is unable to identify that base branch has been changed.

**Pull request closed without merging**
